### ISSUE TITLE
Deploy GIVpower contract for production

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/givpower#27]
@aminlatifi commented on [Thu Sep 29 2022](https://github.com/Giveth/GIVeconomy/issues/727)

I have deployed this 
https://blockscout.com/xdai/mainnet/address/0x2a65518f224963854B9814d6186Ecc093796B02B

The `INITIAL_DATE` is 4 days after tokenDistro start time (https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229) in order to match with 4 days shift in givback round

**Comment by aminlatifi** [comment]
@KurtMerbeth Would you please review the deployed contract? 
The next step is creating upgrade transaction on multi-sig

**Comment by KurtMerbeth** [comment]
@aminlatifi looks good

**Comment by aminlatifi** [comment]
Thanks

**Comment by aminlatifi** [comment]
I prepared a multisig transaction to upgrade the contract 
https://gnosis-safe.io/app/gno:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/multisig_0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd_0x5ff4f66d40b08b04f94532555e9c4f172fa5c4e6762f40b2704f87008f90e6c5

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/5684607/192974870-750a188f-0741-4f3d-a50e-42ccb43e705a.png">

@laurenluz it's worth to be checked by others, @divine-comedian was good on it.

**Comment by aminlatifi** [comment]
The contract is upgraded by a second implementation version 0x4bcB3397420af3227835f053Ff79B3Fe6bbCB9ed
